### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by rmsa5** [hatoving/GMSVitaPortInstructions#1]
Tried following your instructions to patched Fran Bow Chapter1 (from the Android release : apk of the 2.0.3 version on the google play store).
I'm using a Mac so deltapatcher is not usable, using multipatch, an equivalent utility.
Instruction are unclear regarding :

- how to go from paying + installing a game on the android device to retrieving the actual apk (I use titanium backup but not everyone knows how to do so, especially since with google drms, it makes no sense to backup apks these days)
- "Go to APK File -> assets and get the file called game.droid and all of its assets in the assets folder with it." So basically we need the whole contents of the assets forlder. Why not just say : copy-paste the whole assets folder to another place ? Rather unclear
- "Select the "Original file" as the OG data.win/game.droid file and the "XDelta patch" as the .xdelta file for your game form the .zip". kinda confusing. You previously instructed to rename the data.win/game.droid file to "game.win". Why not refer to "game.win" then?
- The xdelta patch doesn't seem to work (at least with multipatch). Utility says "Invalid input. This typically means that the file you selected to patch is not the file your patch is intended for.". Are we sure the xdelta file you provided is compatible with the latest version of Fran Bow Chapter1 2.0.3 ?
- If the only file that has to be sent to the vita is the patched version of the game.win, then what was the point in copy-pasting all the assets besides game.win (all the png, ogg,... files?) in the work folder before applying the patch? Unclear and confusing what to do. Did the xdelta patching process somehow take the original game.win + all the separate other assets files, and merge them all into the patched game.win ?

Thanks in advance

NB: I'm using the updated version of your xdelta patch release for this game.

**Comment by enroag** [comment]
Hi @mightysashiman,
I had the same issues as you, it has to look like this in your PSVITA:
![image](https://user-images.githubusercontent.com/72501058/114270059-8c5a2300-9a0a-11eb-949c-d1b70dc8bf6b.png)

I hope this helps.

Best regards

**Comment by hatoving** [comment]
Hi there! I have to be honest, I kind rushed the instructions, because Rinnegatamante told me it would be better if I set-up clear instructions. It was already late at night, and I wanted to get the game released on VitaDB and the patch on the GIthub page, so went ahead and rushed it as fast I could. So sorry if anyone has trouble installing it! 

Basically, take all of the contents from assets folder, put them in a safe place, then patch the xDelta file with it. 
(_Note, I really needed to put the "This is for Windows only" thing there..._)
Also, I made the patch using DeltaPatcher. As for Mac users, try using Wine. Thanks for explaning the issues tho! Again, so sorry! Will fix up the instructions!

(_Another note, the `game.win` file is to be patched to make the game actually boot._ Also, the patch files work for me as intended, I'll try to work into the issue.)

-hatoving
